### ISSUE TITLE
Hydra reset script doesn't set audience, breaking DAM login

### ISSUE THREAD

**Issue by monicavalluri** [GoogleCloudPlatform/healthcare-federated-access-services#15]
Fix in [fork](https://github.com/DNAstack/healthcare-federated-access-services/commit/2a9a647cefd364987cbdb1a37d93fe2c656d91d)

**Comment by chaopeng** [comment]
chaopeng@ checkout the fork see how to fix

**Comment by cdvoisin** [comment]
Hydra script no longer needed. Now removed.
