### ISSUE TITLE
User information unavailable in ddap-dam-admin

### ISSUE THREAD

**Issue by monicavalluri** [GoogleCloudPlatform/healthcare-federated-access-services#16]
Currently, we can't get information about users after a DAM login. Should userinfo have this information, or will the DAM implement SCIM?

**Comment by chaopeng** [comment]
Need to also copy "profile" info to hydra when request will scope "profile"

**Comment by mbarkley** [comment]
We have a slight fix on our fork that adds email addresses that we can work on a PR for.

**Comment by cdvoisin** [comment]
Fixed in v0.9.6
