### ISSUE TITLE
Getting 404 error on button "Auth for Resources" in damdemo.

### ISSUE THREAD

**Issue by shuklashashank** [GoogleCloudPlatform/healthcare-federated-access-services#41]
I have deployed the GA4GH by using `deploy.bash`. It deploys SQL, GAE services easily but while clicking the "Auth for Resources" button getting 404 not found error (host-link https://damdemo-staging-dot-health-246205.uc.r.appspot.com/test). Are there any `Oauth keys` needed to be set up first.
There is also a `502 Bad Gateway` error after clicking the log-in button in the icdemo-test link. (https://icdemo-staging-dot-health-246205.uc.r.appspot.com/test)
Also, if you can share the whole process doc it would be helpful.

**Comment by chaopeng** [comment]
Please go through this doc https://github.com/GoogleCloudPlatform/healthcare-federated-access-services/blob/master/deploy.md

**Comment by shuklashashank** [comment]
@chaopeng I deployed the application with the above shred link, getting 404 and 502 errors as mentioned in the question.

**Comment by chaopeng** [comment]
I think your ic and dam not actually running, see  https://dam-staging-dot-health-246205.uc.r.appspot.com/dam. Did you go run prepare_project.bash to setup the project? other than that a log from stackdriver may help to see why ic/dam crash on start.

**Comment by shuklashashank** [comment]
It is showing the error:
`level=fatal msg="Unable to instantiate service registry." error="could not ping SQL connection: failed to connect to host=172.17.0.1 user=hydra database=dam-staging: dial error (dial tcp 172.17.0.1:1234: connect: connection refused)"`

I've seen a few variables are defined in `entrypoint.bash`. Do I need to update those?

**Comment by chaopeng** [comment]
It seems like the cloudsql does not setup, you will need to run `prepare_project.bash` to setup the gcp project

**Comment by shuklashashank** [comment]
dam-demo is showing the below error:
```ERROR: (gcloud.beta.app.deploy) Error Response: [4] Your deployment has failed to become healthy in the allotted time and therefore was rolled back. If you believe this was an error, try adjusting the 'app_start_timeout_sec' setting in the 'readiness_check' section.```
How can I check the logs or do I need to increase the timeout_sec?

**Comment by shuklashashank** [comment]
@chaopeng cloud SQL is set up, but there is not any DB created with the name of `dam-staging`. May I know from where it is getting created?

```
SQL connection: failed to connect to `host=172.17.0.1 user=hydra database=dam-staging`: server error (FATAL: database \"dam-staging\" does not exist (SQLSTATE 3D000))
```

**Comment by chaopeng** [comment]
Please run `prepare_project.bash`, or read the script for howto

**Comment by shuklashashank** [comment]
I've gone through the `prepare_project.bash` there are only two databases getting created.
https://github.com/GoogleCloudPlatform/healthcare-federated-access-services/blob/b5db0b7ca103613add626bb5d5fd9dbf514a2135/prepare_project.bash#L106

**Comment by shuklashashank** [comment]
@chaopeng I've created the DB.

Now getting the new errors,
log

'''
F0709 17:55:17.363760      18 dam.go:263] cannot load adapters: error creating AWS key warehouse: NoCredentialProviders: no valid providers in chain. Deprecated
For verbose messaging see aws.Config.CredentialsChainVerboseErrors
'''

**Comment by chaopeng** [comment]
@mbarkley I have never seen this before, it seems like @shuklashashank config has asw adapter, do you know what is related?

**Comment by mbarkley** [comment]
@chaopeng the AWS adapter does some initialization that fails fast if no AWS credentials are configured in the deployment environment. To solve this problem, we'd need to make one of the following code changes:
1. Lazy initialize the AWS adapter (this means we'd fail late for users that do want to use AWS)
2. Add configuration to disable the AWS adapter so that it is not initialized at all in `adapters.go`

**Comment by shashank-mediaagilty** [comment]
@chaopeng Hi getting OAuth2 request resulted in an error. Can you help me with it, how can I configure this. where are the keys getting initialised.

**Comment by shuklashashank** [comment]
@chaopeng Hi getting OAuth2 request resulted in an error. Can you help me with it, how can I configure this. where are the keys getting initialized?
