### ISSUE TITLE
DAM asks for consent after choosing remember while logging in

### ISSUE THREAD

**Issue by monicavalluri** [GoogleCloudPlatform/healthcare-federated-access-services#42]
Select remember consents while logging in, consents would be displayed in the dashboard. But consent is asked for any subsequent login.

After some debugging, I found that there is an error while reading RememberedConsent from storage. 
Error: `rpc error: code = NotFound desc = not found: "/entity,dam/remembered_consent/master/dam_b3611ddc529e4550a9e45841a6/dam_b3611ddc529e4550a9e45841a6/latest"`

The `hydraConsentRememberConsentOrInformationReleasePage` method does not return when the error occurred because of this logic:
```
if err != nil && !storage.ErrNotFound(err) {
	return nil, status.Errorf(codes.Internal, "read remembered consent failed: %v", err)
}
```

**Comment by chaopeng** [comment]
I see the issue is related to realm.
