### ISSUE TITLE
Cannot create/update Identity Concentrator IDP without setting/updating client secret

### ISSUE THREAD

**Issue by mbarkley** [GoogleCloudPlatform/healthcare-federated-access-services#51]
In v0.9.11, you cannot create or update an IDP in the IC without setting the newly introduced `clientSecret` attribute.

Reproducer:
1. Create a valid POST/PUT request for an IDP to the IC, with all fields except the new `clientSecret` set

Expected: either 200 with client created/updated, or an error of some kind if `clientSecret` is mandatory.

Observed: a 200, but none of the changes are persisted; a POST does not result in a new client; a PUT does not result in changes persisted to the IDP.

If you use the `clientSecret` attribute, everything works as expected.

**Comment by chaopeng** [comment]
https://github.com/GoogleCloudPlatform/healthcare-federated-access-services/commit/fc97af53e675a70358da102abf723d9c6e1fac8e
